In [1]:

from Agents import SmartAgent

In [2]:

# 1. 初始化棋盘

In [3]:
import numpy as np

In [4]:
def printState(state):
    state = state.astype(int)
    print(state[0:3])
    print(state[3:6])
    print(state[6:9])
    print()


def isEndState(state):
    # 如果棋局没有结束，就返回0
    # 如果1赢了，就返回1
    # 如果2赢了，就返回2
    # 如果平局，返回-1

    # 横着的出现3个
    state = state.astype(int)
    for i in [0, 3, 6]:
        if state[i] and state[i]==state[i+1] and state[i+1]==state[i+2]:
            return state[i]
        
    # 竖着的出现3个
    for i in [0, 1, 2]:
        if state[i] and state[i]==state[i+3*1] and state[i+3*1]==state[i+3*2]:
            return state[i]
    
    # 斜着的
    if state[0] and state[0]==state[4] and state[0]==state[8]:
        return state[4]
    
    if state[2] and state[2]==state[4] and state[4]==state[6]:
        return state[4]
    
    for qizi in state:
        if qizi==0:#棋局没有结束
            return 0
        
    return -1


In [5]:
state=np.zeros(9)

In [6]:
state[0]=2
state[1]=2
state[4]=2
state[5]=2
state[6]=2

state[2]=1
state[3]=1
state[7]=1
state[8]=1

In [7]:
isEndState(state)

-1

In [8]:
agent1 = SmartAgent(OOXX_index=1)


In [9]:
winNum=0
for epoch in range(100000):
    # 10局
    round = True
    agent1.reset()

    
    while not isEndState(agent1.currentState):
        # 棋局没有结束，继续下棋

        if round: # agent1下
            round = not round

            actionState = agent1.actionTake(agent1.currentState)
            
            if isEndState(actionState)==1:
                # 如果赢棋了，所选动作导致的状态函数价值+10
                agent1.value[tuple(actionState.astype(int))] += 10
                winNum += 1
            agent1.valueUpdate(actionState)

            #if epoch%10000==0:
            # printState(agent1.currentState)


        else:#随机agent下
            round = not round

            available = np.where(agent1.currentState==0)[0]
            length = len(available)
            choose = np.random.randint(length)
            agent1.currentState[available[choose]] = 2
            #printState(agent1.currentState)

    
    #if epoch%10000==0:
    # print('-'*20)


print(winNum)
# 10万次，赢了84855次

84855


In [15]:
agent1.reset()
agent1.epsilon=0

In [32]:
agent1.currentState = agent1.actionTake(agent1.currentState)

In [33]:
printState(agent1.currentState)

[2 1 1]
[1 2 2]
[1 2 1]



In [30]:
available = np.where(agent1.currentState==0)[0]
length = len(available)
choose = np.random.randint(length)
agent1.currentState[available[choose]] = 2

In [31]:
printState(agent1.currentState)

[2 0 1]
[1 2 2]
[1 2 1]

