In [1]:

from Agents import SmartAgent

In [2]:

# 1. 初始化棋盘

In [3]:
import numpy as np

In [4]:
def printState(state):
    state = state.astype(int)
    print(state[0:3])
    print(state[3:6])
    print(state[6:9])
    print()


def isEndState(state):
    # 如果棋局没有结束，就返回0
    # 如果1赢了，就返回1
    # 如果2赢了，就返回2
    # 如果平局，返回-1

    # 横着的出现3个
    state = state.astype(int)
    for i in [0, 3, 6]:
        if state[i] and state[i]==state[i+1] and state[i+1]==state[i+2]:
            return state[i]
        
    # 竖着的出现3个
    for i in [0, 1, 2]:
        if state[i] and state[i]==state[i+3*1] and state[i+3*1]==state[i+3*2]:
            return state[i]
    
    # 斜着的
    if state[0] and state[0]==state[4] and state[0]==state[8]:
        return state[4]
    
    if state[2] and state[2]==state[4] and state[4]==state[6]:
        return state[4]
    
    for qizi in state:
        if qizi==0:#棋局没有结束
            return 0
        
    return -1


In [5]:
state=np.zeros(9)

In [6]:
state[0]=2
state[1]=2
state[4]=2
state[5]=2
state[6]=2

state[2]=1
state[3]=1
state[7]=1
state[8]=1

In [7]:
isEndState(state)

-1

In [8]:
agent1 = SmartAgent(OOXX_index=1, Epsilon=0.2)
agent2 = SmartAgent(OOXX_index=2, Epsilon=0.2)


agent1.epsilon=0
agent2.epsilon=0


In [9]:
win1Num=0
win2Num=0
for epoch in range(400000):
    # 10局
    round = True
    agent1.reset()
    agent2.reset()

    
    vsState = agent1.currentState

    while not isEndState(agent1.currentState):
        # 棋局没有结束，继续下棋

        if round: # agent1下
            round = not round

            vsState = agent1.actionTake(vsState)
            
            if isEndState(vsState)==1:
                # 如果赢棋了，所选动作导致的状态函数价值+10
                agent1.value[tuple(vsState.astype(int))] += 20
                win1Num += 1
                break
            agent1.valueUpdate(vsState)


        else:#agent2下
            round = not round
            vsState = agent2.actionTake(vsState)
            
            if isEndState(vsState)==2:
                # 如果赢棋了，所选动作导致的状态函数价值+10
                agent2.value[tuple(vsState.astype(int))] += 20
                win2Num += 1
                break
            agent2.valueUpdate(vsState)

    
    #if epoch%10000==0:
    # print('-'*20)


print(win1Num)
print(win2Num)


265800
112630


In [10]:
agent1.epsilon=0
agent2.epsilon=0

In [11]:
agent1.reset()
agent2.reset()

In [24]:
agent1.currentState = agent1.actionTake(agent2.currentState)

In [25]:
printState(agent1.currentState)

[1 2 0]
[2 2 0]
[1 1 1]



In [22]:
agent2.currentState = agent2.actionTake(agent1.currentState)

In [23]:
printState(agent2.currentState)

[1 2 0]
[2 2 0]
[1 1 0]



如果有些状态不是整数怎么办

很多状态难以搜索怎么办